## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  imagePullPolicy: IfNotPresent
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []

## @section Common Parameters
##

nameOverride: ""
fullnameOverride: ""

## @section backup
##
backup:
  name: backup
  enabled: true

  schedule: ""

  # existingClaim 和 nodeSelector 至少有一个
  existingClaim: ""

  hostPath: ""

  ## env
  env:
    {}
    ## e.g:
    ## 必填
    ## MONGO_URI:
    ## MONGO_FILE_PREFIX:
    ## BACKUP_LATEST_FILE:
    ## 选填
    ## BACKUP_PATH:
    ## BACKUP_SAVE_NUMS:
    ## MONGO_DB:
    ## MONGO_COLLECTION:
    ## MONGO_EXCLUDE_COLLECTIONS:
    ## BACKUP_PWD:

  image:
    registry: ""
    repository: 36node/mongodb-backup
    tag: main
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: ""
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
    ## Enable debug mode
    ##
    debug: false

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## Configure resource requests and limits
  nodeSelector: {}

  ## Configure tolerations
  tolerations: []

  ## Configure affinity
  affinity: {}

  ## Configure pod annotations
  podAnnotations: {}

## @section restore
##
restore:
  name: restore
  enabled: true

  # existingClaim 和 nodeSelector 至少有一个
  existingClaim: ""

  hostPath: ""

  ## env
  env:
    {}
    ## e.g:
    ## 必填
    ## MONGO_URI:
    ## MONGO_FILE_PREFIX:
    ## BACKUP_LATEST_FILE:
    ## 选填
    ## BACKUP_PATH:
    ## BACKUP_PWD:

  image:
    registry: ""
    repository: 36node/mongodb-backup
    tag: main
    digest: ""
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: ""
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ## e.g:
    ## pullSecrets:
    ##   - myRegistryKeySecretName
    ##
    pullSecrets: []
    ## Enable debug mode
    ##
    debug: false

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  ## Configure resource requests and limits
  nodeSelector: {}

  ## Configure tolerations
  tolerations: []

  ## Configure affinity
  affinity: {}

  ## Configure pod annotations
  podAnnotations: {}
